// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: points-system/v1/point.proto

package v1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 错误码枚举
type ErrorCode int32

const (
	ErrorCode_UNKNOWN_ERROR       ErrorCode = 0
	ErrorCode_POINTS_INSUFFICIENT ErrorCode = 1 // 积分不足
	ErrorCode_OPERATION_FAILED    ErrorCode = 2
	ErrorCode_INVALID_REQUEST     ErrorCode = 3
	ErrorCode_NONE_ERROR          ErrorCode = 4 // 无错误
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0: "UNKNOWN_ERROR",
		1: "POINTS_INSUFFICIENT",
		2: "OPERATION_FAILED",
		3: "INVALID_REQUEST",
		4: "NONE_ERROR",
	}
	ErrorCode_value = map[string]int32{
		"UNKNOWN_ERROR":       0,
		"POINTS_INSUFFICIENT": 1,
		"OPERATION_FAILED":    2,
		"INVALID_REQUEST":     3,
		"NONE_ERROR":          4,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_points_system_v1_point_proto_enumTypes[0].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_points_system_v1_point_proto_enumTypes[0]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_points_system_v1_point_proto_rawDescGZIP(), []int{0}
}

// 用户信息
type UserInfo struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	UserId             string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username           string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Experience         int64                  `protobuf:"varint,3,opt,name=experience,proto3" json:"experience,omitempty"`                                             // 当前经验值
	Points             int64                  `protobuf:"varint,4,opt,name=points,proto3" json:"points,omitempty"`                                                     // 当前积分
	Level              int32                  `protobuf:"varint,5,opt,name=level,proto3" json:"level,omitempty"`                                                       // 当前等级
	IsSigned           bool                   `protobuf:"varint,6,opt,name=is_signed,json=isSigned,proto3" json:"is_signed,omitempty"`                                 // 是否已签到
	ContinuousSignDays int32                  `protobuf:"varint,7,opt,name=continuous_sign_days,json=continuousSignDays,proto3" json:"continuous_sign_days,omitempty"` // 连续签到天数
	TotalSignDays      int32                  `protobuf:"varint,8,opt,name=total_sign_days,json=totalSignDays,proto3" json:"total_sign_days,omitempty"`                // 总签到天数
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	mi := &file_points_system_v1_point_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_points_system_v1_point_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_points_system_v1_point_proto_rawDescGZIP(), []int{0}
}

func (x *UserInfo) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserInfo) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserInfo) GetExperience() int64 {
	if x != nil {
		return x.Experience
	}
	return 0
}

func (x *UserInfo) GetPoints() int64 {
	if x != nil {
		return x.Points
	}
	return 0
}

func (x *UserInfo) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *UserInfo) GetIsSigned() bool {
	if x != nil {
		return x.IsSigned
	}
	return false
}

func (x *UserInfo) GetContinuousSignDays() int32 {
	if x != nil {
		return x.ContinuousSignDays
	}
	return 0
}

func (x *UserInfo) GetTotalSignDays() int32 {
	if x != nil {
		return x.TotalSignDays
	}
	return 0
}

// 积分/经验变更请求
type UpdatePointsRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DeltaPoints     int64                  `protobuf:"varint,2,opt,name=delta_points,json=deltaPoints,proto3" json:"delta_points,omitempty"`             // 积分变化量（正加负扣）
	DeltaExperience int64                  `protobuf:"varint,3,opt,name=delta_experience,json=deltaExperience,proto3" json:"delta_experience,omitempty"` // 经验变化量
	Reason          string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`                                           // 变更原因（如"签到"、"发帖"）
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdatePointsRequest) Reset() {
	*x = UpdatePointsRequest{}
	mi := &file_points_system_v1_point_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePointsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePointsRequest) ProtoMessage() {}

func (x *UpdatePointsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_points_system_v1_point_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePointsRequest.ProtoReflect.Descriptor instead.
func (*UpdatePointsRequest) Descriptor() ([]byte, []int) {
	return file_points_system_v1_point_proto_rawDescGZIP(), []int{1}
}

func (x *UpdatePointsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdatePointsRequest) GetDeltaPoints() int64 {
	if x != nil {
		return x.DeltaPoints
	}
	return 0
}

func (x *UpdatePointsRequest) GetDeltaExperience() int64 {
	if x != nil {
		return x.DeltaExperience
	}
	return 0
}

func (x *UpdatePointsRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// 通用响应
type CommonResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ErrorCode     ErrorCode              `protobuf:"varint,3,opt,name=error_code,json=errorCode,proto3,enum=mundo.system.point.ErrorCode" json:"error_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommonResponse) Reset() {
	*x = CommonResponse{}
	mi := &file_points_system_v1_point_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonResponse) ProtoMessage() {}

func (x *CommonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_points_system_v1_point_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonResponse.ProtoReflect.Descriptor instead.
func (*CommonResponse) Descriptor() ([]byte, []int) {
	return file_points_system_v1_point_proto_rawDescGZIP(), []int{2}
}

func (x *CommonResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CommonResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CommonResponse) GetErrorCode() ErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return ErrorCode_UNKNOWN_ERROR
}

// 点赞请求
type LikeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PostId        string                 `protobuf:"bytes,2,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	TargetUserId  string                 `protobuf:"bytes,3,opt,name=target_user_id,json=targetUserId,proto3" json:"target_user_id,omitempty"` // 被点赞的用户ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeRequest) Reset() {
	*x = LikeRequest{}
	mi := &file_points_system_v1_point_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeRequest) ProtoMessage() {}

func (x *LikeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_points_system_v1_point_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeRequest.ProtoReflect.Descriptor instead.
func (*LikeRequest) Descriptor() ([]byte, []int) {
	return file_points_system_v1_point_proto_rawDescGZIP(), []int{3}
}

func (x *LikeRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *LikeRequest) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *LikeRequest) GetTargetUserId() string {
	if x != nil {
		return x.TargetUserId
	}
	return ""
}

// 获取用户信息请求
type GetUserInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInfoRequest) Reset() {
	*x = GetUserInfoRequest{}
	mi := &file_points_system_v1_point_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoRequest) ProtoMessage() {}

func (x *GetUserInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_points_system_v1_point_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoRequest.ProtoReflect.Descriptor instead.
func (*GetUserInfoRequest) Descriptor() ([]byte, []int) {
	return file_points_system_v1_point_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserInfoRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// 签到请求
type SignRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignRequest) Reset() {
	*x = SignRequest{}
	mi := &file_points_system_v1_point_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignRequest) ProtoMessage() {}

func (x *SignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_points_system_v1_point_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignRequest.ProtoReflect.Descriptor instead.
func (*SignRequest) Descriptor() ([]byte, []int) {
	return file_points_system_v1_point_proto_rawDescGZIP(), []int{5}
}

func (x *SignRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// 签到响应
type SignResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Success            bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message            string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ErrorCode          ErrorCode              `protobuf:"varint,3,opt,name=error_code,json=errorCode,proto3,enum=mundo.system.point.ErrorCode" json:"error_code,omitempty"`
	Points             int64                  `protobuf:"varint,4,opt,name=points,proto3" json:"points,omitempty"`                                                     // 签到获得的积分
	Experience         int64                  `protobuf:"varint,5,opt,name=experience,proto3" json:"experience,omitempty"`                                             // 签到获得的经验
	ContinuousSignDays int32                  `protobuf:"varint,6,opt,name=continuous_sign_days,json=continuousSignDays,proto3" json:"continuous_sign_days,omitempty"` // 连续签到天数
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SignResponse) Reset() {
	*x = SignResponse{}
	mi := &file_points_system_v1_point_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignResponse) ProtoMessage() {}

func (x *SignResponse) ProtoReflect() protoreflect.Message {
	mi := &file_points_system_v1_point_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignResponse.ProtoReflect.Descriptor instead.
func (*SignResponse) Descriptor() ([]byte, []int) {
	return file_points_system_v1_point_proto_rawDescGZIP(), []int{6}
}

func (x *SignResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SignResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SignResponse) GetErrorCode() ErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return ErrorCode_UNKNOWN_ERROR
}

func (x *SignResponse) GetPoints() int64 {
	if x != nil {
		return x.Points
	}
	return 0
}

func (x *SignResponse) GetExperience() int64 {
	if x != nil {
		return x.Experience
	}
	return 0
}

func (x *SignResponse) GetContinuousSignDays() int32 {
	if x != nil {
		return x.ContinuousSignDays
	}
	return 0
}

// 后台统计数据
type AdminStats struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	LevelDistribution []*LevelDistribution   `protobuf:"bytes,1,rep,name=level_distribution,json=levelDistribution,proto3" json:"level_distribution,omitempty"`
	AvgPoints         float32                `protobuf:"fixed32,2,opt,name=avg_points,json=avgPoints,proto3" json:"avg_points,omitempty"`
	MonthlyPointsUsed int64                  `protobuf:"varint,3,opt,name=monthly_points_used,json=monthlyPointsUsed,proto3" json:"monthly_points_used,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AdminStats) Reset() {
	*x = AdminStats{}
	mi := &file_points_system_v1_point_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminStats) ProtoMessage() {}

func (x *AdminStats) ProtoReflect() protoreflect.Message {
	mi := &file_points_system_v1_point_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminStats.ProtoReflect.Descriptor instead.
func (*AdminStats) Descriptor() ([]byte, []int) {
	return file_points_system_v1_point_proto_rawDescGZIP(), []int{7}
}

func (x *AdminStats) GetLevelDistribution() []*LevelDistribution {
	if x != nil {
		return x.LevelDistribution
	}
	return nil
}

func (x *AdminStats) GetAvgPoints() float32 {
	if x != nil {
		return x.AvgPoints
	}
	return 0
}

func (x *AdminStats) GetMonthlyPointsUsed() int64 {
	if x != nil {
		return x.MonthlyPointsUsed
	}
	return 0
}

// 等级分布
type LevelDistribution struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         int32                  `protobuf:"varint,1,opt,name=level,proto3" json:"level,omitempty"`
	UserCount     int64                  `protobuf:"varint,2,opt,name=user_count,json=userCount,proto3" json:"user_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LevelDistribution) Reset() {
	*x = LevelDistribution{}
	mi := &file_points_system_v1_point_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LevelDistribution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LevelDistribution) ProtoMessage() {}

func (x *LevelDistribution) ProtoReflect() protoreflect.Message {
	mi := &file_points_system_v1_point_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LevelDistribution.ProtoReflect.Descriptor instead.
func (*LevelDistribution) Descriptor() ([]byte, []int) {
	return file_points_system_v1_point_proto_rawDescGZIP(), []int{8}
}

func (x *LevelDistribution) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *LevelDistribution) GetUserCount() int64 {
	if x != nil {
		return x.UserCount
	}
	return 0
}

var File_points_system_v1_point_proto protoreflect.FileDescriptor

const file_points_system_v1_point_proto_rawDesc = "" +
	"\n" +
	"\x1cpoints-system/v1/point.proto\x12\x12mundo.system.point\"\x84\x02\n" +
	"\bUserInfo\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1e\n" +
	"\n" +
	"experience\x18\x03 \x01(\x03R\n" +
	"experience\x12\x16\n" +
	"\x06points\x18\x04 \x01(\x03R\x06points\x12\x14\n" +
	"\x05level\x18\x05 \x01(\x05R\x05level\x12\x1b\n" +
	"\tis_signed\x18\x06 \x01(\bR\bisSigned\x120\n" +
	"\x14continuous_sign_days\x18\a \x01(\x05R\x12continuousSignDays\x12&\n" +
	"\x0ftotal_sign_days\x18\b \x01(\x05R\rtotalSignDays\"\x94\x01\n" +
	"\x13UpdatePointsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12!\n" +
	"\fdelta_points\x18\x02 \x01(\x03R\vdeltaPoints\x12)\n" +
	"\x10delta_experience\x18\x03 \x01(\x03R\x0fdeltaExperience\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\"\x82\x01\n" +
	"\x0eCommonResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12<\n" +
	"\n" +
	"error_code\x18\x03 \x01(\x0e2\x1d.mundo.system.point.ErrorCodeR\terrorCode\"e\n" +
	"\vLikeRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\apost_id\x18\x02 \x01(\tR\x06postId\x12$\n" +
	"\x0etarget_user_id\x18\x03 \x01(\tR\ftargetUserId\"-\n" +
	"\x12GetUserInfoRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"&\n" +
	"\vSignRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\xea\x01\n" +
	"\fSignResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12<\n" +
	"\n" +
	"error_code\x18\x03 \x01(\x0e2\x1d.mundo.system.point.ErrorCodeR\terrorCode\x12\x16\n" +
	"\x06points\x18\x04 \x01(\x03R\x06points\x12\x1e\n" +
	"\n" +
	"experience\x18\x05 \x01(\x03R\n" +
	"experience\x120\n" +
	"\x14continuous_sign_days\x18\x06 \x01(\x05R\x12continuousSignDays\"\xb1\x01\n" +
	"\n" +
	"AdminStats\x12T\n" +
	"\x12level_distribution\x18\x01 \x03(\v2%.mundo.system.point.LevelDistributionR\x11levelDistribution\x12\x1d\n" +
	"\n" +
	"avg_points\x18\x02 \x01(\x02R\tavgPoints\x12.\n" +
	"\x13monthly_points_used\x18\x03 \x01(\x03R\x11monthlyPointsUsed\"H\n" +
	"\x11LevelDistribution\x12\x14\n" +
	"\x05level\x18\x01 \x01(\x05R\x05level\x12\x1d\n" +
	"\n" +
	"user_count\x18\x02 \x01(\x03R\tuserCount*r\n" +
	"\tErrorCode\x12\x11\n" +
	"\rUNKNOWN_ERROR\x10\x00\x12\x17\n" +
	"\x13POINTS_INSUFFICIENT\x10\x01\x12\x14\n" +
	"\x10OPERATION_FAILED\x10\x02\x12\x13\n" +
	"\x0fINVALID_REQUEST\x10\x03\x12\x0e\n" +
	"\n" +
	"NONE_ERROR\x10\x042\xc6\x03\n" +
	"\vUserService\x12K\n" +
	"\x04Sign\x12\x1f.mundo.system.point.SignRequest\x1a\".mundo.system.point.CommonResponse\x12h\n" +
	"\x19UpdatePointsAndExperience\x12'.mundo.system.point.UpdatePointsRequest\x1a\".mundo.system.point.CommonResponse\x12S\n" +
	"\vGetUserInfo\x12&.mundo.system.point.GetUserInfoRequest\x1a\x1c.mundo.system.point.UserInfo\x12R\n" +
	"\vProcessLike\x12\x1f.mundo.system.point.LikeRequest\x1a\".mundo.system.point.CommonResponse\x12W\n" +
	"\rGetAdminStats\x12&.mundo.system.point.GetUserInfoRequest\x1a\x1e.mundo.system.point.AdminStatsB\xc9\x01\n" +
	"\x16com.mundo.system.pointB\n" +
	"PointProtoP\x01Z9github.com/betterde/focusly/internal/gen/points-system/v1\xa2\x02\x03MSP\xaa\x02\x12Mundo.System.Point\xca\x02\x12Mundo\\System\\Point\xe2\x02\x1eMundo\\System\\Point\\GPBMetadata\xea\x02\x14Mundo::System::Pointb\x06proto3"

var (
	file_points_system_v1_point_proto_rawDescOnce sync.Once
	file_points_system_v1_point_proto_rawDescData []byte
)

func file_points_system_v1_point_proto_rawDescGZIP() []byte {
	file_points_system_v1_point_proto_rawDescOnce.Do(func() {
		file_points_system_v1_point_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_points_system_v1_point_proto_rawDesc), len(file_points_system_v1_point_proto_rawDesc)))
	})
	return file_points_system_v1_point_proto_rawDescData
}

var file_points_system_v1_point_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_points_system_v1_point_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_points_system_v1_point_proto_goTypes = []any{
	(ErrorCode)(0),              // 0: mundo.system.point.ErrorCode
	(*UserInfo)(nil),            // 1: mundo.system.point.UserInfo
	(*UpdatePointsRequest)(nil), // 2: mundo.system.point.UpdatePointsRequest
	(*CommonResponse)(nil),      // 3: mundo.system.point.CommonResponse
	(*LikeRequest)(nil),         // 4: mundo.system.point.LikeRequest
	(*GetUserInfoRequest)(nil),  // 5: mundo.system.point.GetUserInfoRequest
	(*SignRequest)(nil),         // 6: mundo.system.point.SignRequest
	(*SignResponse)(nil),        // 7: mundo.system.point.SignResponse
	(*AdminStats)(nil),          // 8: mundo.system.point.AdminStats
	(*LevelDistribution)(nil),   // 9: mundo.system.point.LevelDistribution
}
var file_points_system_v1_point_proto_depIdxs = []int32{
	0, // 0: mundo.system.point.CommonResponse.error_code:type_name -> mundo.system.point.ErrorCode
	0, // 1: mundo.system.point.SignResponse.error_code:type_name -> mundo.system.point.ErrorCode
	9, // 2: mundo.system.point.AdminStats.level_distribution:type_name -> mundo.system.point.LevelDistribution
	6, // 3: mundo.system.point.UserService.Sign:input_type -> mundo.system.point.SignRequest
	2, // 4: mundo.system.point.UserService.UpdatePointsAndExperience:input_type -> mundo.system.point.UpdatePointsRequest
	5, // 5: mundo.system.point.UserService.GetUserInfo:input_type -> mundo.system.point.GetUserInfoRequest
	4, // 6: mundo.system.point.UserService.ProcessLike:input_type -> mundo.system.point.LikeRequest
	5, // 7: mundo.system.point.UserService.GetAdminStats:input_type -> mundo.system.point.GetUserInfoRequest
	3, // 8: mundo.system.point.UserService.Sign:output_type -> mundo.system.point.CommonResponse
	3, // 9: mundo.system.point.UserService.UpdatePointsAndExperience:output_type -> mundo.system.point.CommonResponse
	1, // 10: mundo.system.point.UserService.GetUserInfo:output_type -> mundo.system.point.UserInfo
	3, // 11: mundo.system.point.UserService.ProcessLike:output_type -> mundo.system.point.CommonResponse
	8, // 12: mundo.system.point.UserService.GetAdminStats:output_type -> mundo.system.point.AdminStats
	8, // [8:13] is the sub-list for method output_type
	3, // [3:8] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_points_system_v1_point_proto_init() }
func file_points_system_v1_point_proto_init() {
	if File_points_system_v1_point_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_points_system_v1_point_proto_rawDesc), len(file_points_system_v1_point_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_points_system_v1_point_proto_goTypes,
		DependencyIndexes: file_points_system_v1_point_proto_depIdxs,
		EnumInfos:         file_points_system_v1_point_proto_enumTypes,
		MessageInfos:      file_points_system_v1_point_proto_msgTypes,
	}.Build()
	File_points_system_v1_point_proto = out.File
	file_points_system_v1_point_proto_goTypes = nil
	file_points_system_v1_point_proto_depIdxs = nil
}
