// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: stat/v1/stat.proto

package statv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TrackEventRequest 上报事件请求
type TrackEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventType     string                 `protobuf:"bytes,1,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"` // 事件类型
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                 // 事件时间戳（毫秒）
	UserId        uint32                 `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`         // 用户 ID
	Ip            string                 `protobuf:"bytes,4,opt,name=ip,proto3" json:"ip,omitempty"`                                // IP 地址
	Source        string                 `protobuf:"bytes,5,opt,name=source,proto3" json:"source,omitempty"`                        // 来源（如 user_agent）
	Properties    string                 `protobuf:"bytes,6,opt,name=properties,proto3" json:"properties,omitempty"`                // 事件属性（JSON 字符串）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrackEventRequest) Reset() {
	*x = TrackEventRequest{}
	mi := &file_stat_v1_stat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackEventRequest) ProtoMessage() {}

func (x *TrackEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stat_v1_stat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackEventRequest.ProtoReflect.Descriptor instead.
func (*TrackEventRequest) Descriptor() ([]byte, []int) {
	return file_stat_v1_stat_proto_rawDescGZIP(), []int{0}
}

func (x *TrackEventRequest) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *TrackEventRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *TrackEventRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *TrackEventRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *TrackEventRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *TrackEventRequest) GetProperties() string {
	if x != nil {
		return x.Properties
	}
	return ""
}

// TrackEventResponse 上报事件响应
type TrackEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"` // 事件 ID
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`               // 是否成功
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`                // 消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrackEventResponse) Reset() {
	*x = TrackEventResponse{}
	mi := &file_stat_v1_stat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackEventResponse) ProtoMessage() {}

func (x *TrackEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stat_v1_stat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackEventResponse.ProtoReflect.Descriptor instead.
func (*TrackEventResponse) Descriptor() ([]byte, []int) {
	return file_stat_v1_stat_proto_rawDescGZIP(), []int{1}
}

func (x *TrackEventResponse) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *TrackEventResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TrackEventResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// TrackEventBatchRequest 批量上报请求
type TrackEventBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*TrackEventRequest   `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"` // 事件列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrackEventBatchRequest) Reset() {
	*x = TrackEventBatchRequest{}
	mi := &file_stat_v1_stat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackEventBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackEventBatchRequest) ProtoMessage() {}

func (x *TrackEventBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stat_v1_stat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackEventBatchRequest.ProtoReflect.Descriptor instead.
func (*TrackEventBatchRequest) Descriptor() ([]byte, []int) {
	return file_stat_v1_stat_proto_rawDescGZIP(), []int{2}
}

func (x *TrackEventBatchRequest) GetEvents() []*TrackEventRequest {
	if x != nil {
		return x.Events
	}
	return nil
}

// TrackEventBatchResponse 批量上报响应
type TrackEventBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SuccessCount  int32                  `protobuf:"varint,1,opt,name=success_count,json=successCount,proto3" json:"success_count,omitempty"` // 成功数量
	FailedCount   int32                  `protobuf:"varint,2,opt,name=failed_count,json=failedCount,proto3" json:"failed_count,omitempty"`    // 失败数量
	EventIds      []string               `protobuf:"bytes,3,rep,name=event_ids,json=eventIds,proto3" json:"event_ids,omitempty"`              // 事件 ID 列表
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`                                // 消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrackEventBatchResponse) Reset() {
	*x = TrackEventBatchResponse{}
	mi := &file_stat_v1_stat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackEventBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackEventBatchResponse) ProtoMessage() {}

func (x *TrackEventBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stat_v1_stat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackEventBatchResponse.ProtoReflect.Descriptor instead.
func (*TrackEventBatchResponse) Descriptor() ([]byte, []int) {
	return file_stat_v1_stat_proto_rawDescGZIP(), []int{3}
}

func (x *TrackEventBatchResponse) GetSuccessCount() int32 {
	if x != nil {
		return x.SuccessCount
	}
	return 0
}

func (x *TrackEventBatchResponse) GetFailedCount() int32 {
	if x != nil {
		return x.FailedCount
	}
	return 0
}

func (x *TrackEventBatchResponse) GetEventIds() []string {
	if x != nil {
		return x.EventIds
	}
	return nil
}

func (x *TrackEventBatchResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_stat_v1_stat_proto protoreflect.FileDescriptor

const file_stat_v1_stat_proto_rawDesc = "" +
	"\n" +
	"\x12stat/v1/stat.proto\x12\astat.v1\"\xb1\x01\n" +
	"\x11TrackEventRequest\x12\x1d\n" +
	"\n" +
	"event_type\x18\x01 \x01(\tR\teventType\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\rR\x06userId\x12\x0e\n" +
	"\x02ip\x18\x04 \x01(\tR\x02ip\x12\x16\n" +
	"\x06source\x18\x05 \x01(\tR\x06source\x12\x1e\n" +
	"\n" +
	"properties\x18\x06 \x01(\tR\n" +
	"properties\"c\n" +
	"\x12TrackEventResponse\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"L\n" +
	"\x16TrackEventBatchRequest\x122\n" +
	"\x06events\x18\x01 \x03(\v2\x1a.stat.v1.TrackEventRequestR\x06events\"\x98\x01\n" +
	"\x17TrackEventBatchResponse\x12#\n" +
	"\rsuccess_count\x18\x01 \x01(\x05R\fsuccessCount\x12!\n" +
	"\ffailed_count\x18\x02 \x01(\x05R\vfailedCount\x12\x1b\n" +
	"\tevent_ids\x18\x03 \x03(\tR\beventIds\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage2\xaa\x01\n" +
	"\vStatService\x12E\n" +
	"\n" +
	"TrackEvent\x12\x1a.stat.v1.TrackEventRequest\x1a\x1b.stat.v1.TrackEventResponse\x12T\n" +
	"\x0fTrackEventBatch\x12\x1f.stat.v1.TrackEventBatchRequest\x1a .stat.v1.TrackEventBatchResponseB\x8e\x01\n" +
	"\vcom.stat.v1B\tStatProtoP\x01Z7github.com/betterde/focusly/internal/gen/stat/v1;statv1\xa2\x02\x03SXX\xaa\x02\aStat.V1\xca\x02\aStat\\V1\xe2\x02\x13Stat\\V1\\GPBMetadata\xea\x02\bStat::V1b\x06proto3"

var (
	file_stat_v1_stat_proto_rawDescOnce sync.Once
	file_stat_v1_stat_proto_rawDescData []byte
)

func file_stat_v1_stat_proto_rawDescGZIP() []byte {
	file_stat_v1_stat_proto_rawDescOnce.Do(func() {
		file_stat_v1_stat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_stat_v1_stat_proto_rawDesc), len(file_stat_v1_stat_proto_rawDesc)))
	})
	return file_stat_v1_stat_proto_rawDescData
}

var file_stat_v1_stat_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_stat_v1_stat_proto_goTypes = []any{
	(*TrackEventRequest)(nil),       // 0: stat.v1.TrackEventRequest
	(*TrackEventResponse)(nil),      // 1: stat.v1.TrackEventResponse
	(*TrackEventBatchRequest)(nil),  // 2: stat.v1.TrackEventBatchRequest
	(*TrackEventBatchResponse)(nil), // 3: stat.v1.TrackEventBatchResponse
}
var file_stat_v1_stat_proto_depIdxs = []int32{
	0, // 0: stat.v1.TrackEventBatchRequest.events:type_name -> stat.v1.TrackEventRequest
	0, // 1: stat.v1.StatService.TrackEvent:input_type -> stat.v1.TrackEventRequest
	2, // 2: stat.v1.StatService.TrackEventBatch:input_type -> stat.v1.TrackEventBatchRequest
	1, // 3: stat.v1.StatService.TrackEvent:output_type -> stat.v1.TrackEventResponse
	3, // 4: stat.v1.StatService.TrackEventBatch:output_type -> stat.v1.TrackEventBatchResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_stat_v1_stat_proto_init() }
func file_stat_v1_stat_proto_init() {
	if File_stat_v1_stat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stat_v1_stat_proto_rawDesc), len(file_stat_v1_stat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_stat_v1_stat_proto_goTypes,
		DependencyIndexes: file_stat_v1_stat_proto_depIdxs,
		MessageInfos:      file_stat_v1_stat_proto_msgTypes,
	}.Build()
	File_stat_v1_stat_proto = out.File
	file_stat_v1_stat_proto_goTypes = nil
	file_stat_v1_stat_proto_depIdxs = nil
}
