// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: forum_pb/forum.proto

package forum_pb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateForumPostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateForumPostRequest) Reset() {
	*x = CreateForumPostRequest{}
	mi := &file_forum_pb_forum_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateForumPostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateForumPostRequest) ProtoMessage() {}

func (x *CreateForumPostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_forum_pb_forum_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateForumPostRequest.ProtoReflect.Descriptor instead.
func (*CreateForumPostRequest) Descriptor() ([]byte, []int) {
	return file_forum_pb_forum_proto_rawDescGZIP(), []int{0}
}

func (x *CreateForumPostRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateForumPostRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type GetForumPostByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetForumPostByIDRequest) Reset() {
	*x = GetForumPostByIDRequest{}
	mi := &file_forum_pb_forum_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetForumPostByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetForumPostByIDRequest) ProtoMessage() {}

func (x *GetForumPostByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_forum_pb_forum_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetForumPostByIDRequest.ProtoReflect.Descriptor instead.
func (*GetForumPostByIDRequest) Descriptor() ([]byte, []int) {
	return file_forum_pb_forum_proto_rawDescGZIP(), []int{1}
}

func (x *GetForumPostByIDRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListForumPostsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListForumPostsRequest) Reset() {
	*x = ListForumPostsRequest{}
	mi := &file_forum_pb_forum_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListForumPostsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListForumPostsRequest) ProtoMessage() {}

func (x *ListForumPostsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_forum_pb_forum_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListForumPostsRequest.ProtoReflect.Descriptor instead.
func (*ListForumPostsRequest) Descriptor() ([]byte, []int) {
	return file_forum_pb_forum_proto_rawDescGZIP(), []int{2}
}

func (x *ListForumPostsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListForumPostsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListForumPostsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Posts         []*ForumPostResponse   `protobuf:"bytes,1,rep,name=posts,proto3" json:"posts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListForumPostsResponse) Reset() {
	*x = ListForumPostsResponse{}
	mi := &file_forum_pb_forum_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListForumPostsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListForumPostsResponse) ProtoMessage() {}

func (x *ListForumPostsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_forum_pb_forum_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListForumPostsResponse.ProtoReflect.Descriptor instead.
func (*ListForumPostsResponse) Descriptor() ([]byte, []int) {
	return file_forum_pb_forum_proto_rawDescGZIP(), []int{3}
}

func (x *ListForumPostsResponse) GetPosts() []*ForumPostResponse {
	if x != nil {
		return x.Posts
	}
	return nil
}

type UpdateForumPostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateForumPostRequest) Reset() {
	*x = UpdateForumPostRequest{}
	mi := &file_forum_pb_forum_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateForumPostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateForumPostRequest) ProtoMessage() {}

func (x *UpdateForumPostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_forum_pb_forum_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateForumPostRequest.ProtoReflect.Descriptor instead.
func (*UpdateForumPostRequest) Descriptor() ([]byte, []int) {
	return file_forum_pb_forum_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateForumPostRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateForumPostRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateForumPostRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type DeleteForumPostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteForumPostRequest) Reset() {
	*x = DeleteForumPostRequest{}
	mi := &file_forum_pb_forum_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteForumPostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteForumPostRequest) ProtoMessage() {}

func (x *DeleteForumPostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_forum_pb_forum_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteForumPostRequest.ProtoReflect.Descriptor instead.
func (*DeleteForumPostRequest) Descriptor() ([]byte, []int) {
	return file_forum_pb_forum_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteForumPostRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ForumPostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Uid           int64                  `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForumPostResponse) Reset() {
	*x = ForumPostResponse{}
	mi := &file_forum_pb_forum_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForumPostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForumPostResponse) ProtoMessage() {}

func (x *ForumPostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_forum_pb_forum_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForumPostResponse.ProtoReflect.Descriptor instead.
func (*ForumPostResponse) Descriptor() ([]byte, []int) {
	return file_forum_pb_forum_proto_rawDescGZIP(), []int{6}
}

func (x *ForumPostResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ForumPostResponse) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *ForumPostResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ForumPostResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_forum_pb_forum_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_forum_pb_forum_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_forum_pb_forum_proto_rawDescGZIP(), []int{7}
}

var File_forum_pb_forum_proto protoreflect.FileDescriptor

const file_forum_pb_forum_proto_rawDesc = "" +
	"\n" +
	"\x14forum_pb/forum.proto\x12\x05forum\x1a\x1cgoogle/api/annotations.proto\"H\n" +
	"\x16CreateForumPostRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\")\n" +
	"\x17GetForumPostByIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"E\n" +
	"\x15ListForumPostsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\"H\n" +
	"\x16ListForumPostsResponse\x12.\n" +
	"\x05posts\x18\x01 \x03(\v2\x18.forum.ForumPostResponseR\x05posts\"X\n" +
	"\x16UpdateForumPostRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\"(\n" +
	"\x16DeleteForumPostRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"e\n" +
	"\x11ForumPostResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\x03R\x03uid\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\"\a\n" +
	"\x05Empty2\xe9\x03\n" +
	"\fForumService\x12]\n" +
	"\x0fCreateForumPost\x12\x1d.forum.CreateForumPostRequest\x1a\x18.forum.ForumPostResponse\"\x11\x82\xd3\xe4\x93\x02\v:\x01*\"\x06/forum\x12d\n" +
	"\x10GetForumPostByID\x12\x1e.forum.GetForumPostByIDRequest\x1a\x18.forum.ForumPostResponse\"\x16\x82\xd3\xe4\x93\x02\x10b\x01*\x12\v/forum/{id}\x12`\n" +
	"\x0eListForumPosts\x12\x1c.forum.ListForumPostsRequest\x1a\x1d.forum.ListForumPostsResponse\"\x11\x82\xd3\xe4\x93\x02\vb\x01*\x12\x06/forum\x12]\n" +
	"\x0fUpdateForumPost\x12\x1d.forum.UpdateForumPostRequest\x1a\x18.forum.ForumPostResponse\"\x11\x82\xd3\xe4\x93\x02\v:\x01*\x1a\x06/forum\x12S\n" +
	"\x0fDeleteForumPost\x12\x1d.forum.DeleteForumPostRequest\x1a\f.forum.Empty\"\x13\x82\xd3\xe4\x93\x02\r*\v/forum/{id}B~\n" +
	"\tcom.forumB\n" +
	"ForumProtoP\x01Z1github.com/betterde/focusly/internal/gen/forum_pb\xa2\x02\x03FXX\xaa\x02\x05Forum\xca\x02\x05Forum\xe2\x02\x11Forum\\GPBMetadata\xea\x02\x05Forumb\x06proto3"

var (
	file_forum_pb_forum_proto_rawDescOnce sync.Once
	file_forum_pb_forum_proto_rawDescData []byte
)

func file_forum_pb_forum_proto_rawDescGZIP() []byte {
	file_forum_pb_forum_proto_rawDescOnce.Do(func() {
		file_forum_pb_forum_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_forum_pb_forum_proto_rawDesc), len(file_forum_pb_forum_proto_rawDesc)))
	})
	return file_forum_pb_forum_proto_rawDescData
}

var file_forum_pb_forum_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_forum_pb_forum_proto_goTypes = []any{
	(*CreateForumPostRequest)(nil),  // 0: forum.CreateForumPostRequest
	(*GetForumPostByIDRequest)(nil), // 1: forum.GetForumPostByIDRequest
	(*ListForumPostsRequest)(nil),   // 2: forum.ListForumPostsRequest
	(*ListForumPostsResponse)(nil),  // 3: forum.ListForumPostsResponse
	(*UpdateForumPostRequest)(nil),  // 4: forum.UpdateForumPostRequest
	(*DeleteForumPostRequest)(nil),  // 5: forum.DeleteForumPostRequest
	(*ForumPostResponse)(nil),       // 6: forum.ForumPostResponse
	(*Empty)(nil),                   // 7: forum.Empty
}
var file_forum_pb_forum_proto_depIdxs = []int32{
	6, // 0: forum.ListForumPostsResponse.posts:type_name -> forum.ForumPostResponse
	0, // 1: forum.ForumService.CreateForumPost:input_type -> forum.CreateForumPostRequest
	1, // 2: forum.ForumService.GetForumPostByID:input_type -> forum.GetForumPostByIDRequest
	2, // 3: forum.ForumService.ListForumPosts:input_type -> forum.ListForumPostsRequest
	4, // 4: forum.ForumService.UpdateForumPost:input_type -> forum.UpdateForumPostRequest
	5, // 5: forum.ForumService.DeleteForumPost:input_type -> forum.DeleteForumPostRequest
	6, // 6: forum.ForumService.CreateForumPost:output_type -> forum.ForumPostResponse
	6, // 7: forum.ForumService.GetForumPostByID:output_type -> forum.ForumPostResponse
	3, // 8: forum.ForumService.ListForumPosts:output_type -> forum.ListForumPostsResponse
	6, // 9: forum.ForumService.UpdateForumPost:output_type -> forum.ForumPostResponse
	7, // 10: forum.ForumService.DeleteForumPost:output_type -> forum.Empty
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_forum_pb_forum_proto_init() }
func file_forum_pb_forum_proto_init() {
	if File_forum_pb_forum_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_forum_pb_forum_proto_rawDesc), len(file_forum_pb_forum_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_forum_pb_forum_proto_goTypes,
		DependencyIndexes: file_forum_pb_forum_proto_depIdxs,
		MessageInfos:      file_forum_pb_forum_proto_msgTypes,
	}.Build()
	File_forum_pb_forum_proto = out.File
	file_forum_pb_forum_proto_goTypes = nil
	file_forum_pb_forum_proto_depIdxs = nil
}
