// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        (unknown)
// source: timerme_pb/navy.proto

package timerme_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateQuestionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`     //问题标题
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"` //问题内容
	Tags          []string               `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`       //问题标签
	Uid           uint64                 `protobuf:"varint,4,opt,name=uid,proto3" json:"uid,omitempty"`        //用户ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateQuestionRequest) Reset() {
	*x = CreateQuestionRequest{}
	mi := &file_timerme_pb_navy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateQuestionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateQuestionRequest) ProtoMessage() {}

func (x *CreateQuestionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_timerme_pb_navy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateQuestionRequest.ProtoReflect.Descriptor instead.
func (*CreateQuestionRequest) Descriptor() ([]byte, []int) {
	return file_timerme_pb_navy_proto_rawDescGZIP(), []int{0}
}

func (x *CreateQuestionRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateQuestionRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreateQuestionRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *CreateQuestionRequest) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type CreateQuestionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuestionId    uint64                 `protobuf:"varint,1,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"` //问题ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateQuestionResponse) Reset() {
	*x = CreateQuestionResponse{}
	mi := &file_timerme_pb_navy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateQuestionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateQuestionResponse) ProtoMessage() {}

func (x *CreateQuestionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_timerme_pb_navy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateQuestionResponse.ProtoReflect.Descriptor instead.
func (*CreateQuestionResponse) Descriptor() ([]byte, []int) {
	return file_timerme_pb_navy_proto_rawDescGZIP(), []int{1}
}

func (x *CreateQuestionResponse) GetQuestionId() uint64 {
	if x != nil {
		return x.QuestionId
	}
	return 0
}

type ListQuestionIdsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           uint64                 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"` //用户ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListQuestionIdsRequest) Reset() {
	*x = ListQuestionIdsRequest{}
	mi := &file_timerme_pb_navy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListQuestionIdsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListQuestionIdsRequest) ProtoMessage() {}

func (x *ListQuestionIdsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_timerme_pb_navy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListQuestionIdsRequest.ProtoReflect.Descriptor instead.
func (*ListQuestionIdsRequest) Descriptor() ([]byte, []int) {
	return file_timerme_pb_navy_proto_rawDescGZIP(), []int{2}
}

func (x *ListQuestionIdsRequest) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type ListQuestionIdsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuestionIds   []uint64               `protobuf:"varint,1,rep,packed,name=question_ids,json=questionIds,proto3" json:"question_ids,omitempty"` //问题ID列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListQuestionIdsResponse) Reset() {
	*x = ListQuestionIdsResponse{}
	mi := &file_timerme_pb_navy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListQuestionIdsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListQuestionIdsResponse) ProtoMessage() {}

func (x *ListQuestionIdsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_timerme_pb_navy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListQuestionIdsResponse.ProtoReflect.Descriptor instead.
func (*ListQuestionIdsResponse) Descriptor() ([]byte, []int) {
	return file_timerme_pb_navy_proto_rawDescGZIP(), []int{3}
}

func (x *ListQuestionIdsResponse) GetQuestionIds() []uint64 {
	if x != nil {
		return x.QuestionIds
	}
	return nil
}

type CreateAnswerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuestionId    uint64                 `protobuf:"varint,1,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"` //问题ID
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`                          //答案内容
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAnswerRequest) Reset() {
	*x = CreateAnswerRequest{}
	mi := &file_timerme_pb_navy_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAnswerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAnswerRequest) ProtoMessage() {}

func (x *CreateAnswerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_timerme_pb_navy_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAnswerRequest.ProtoReflect.Descriptor instead.
func (*CreateAnswerRequest) Descriptor() ([]byte, []int) {
	return file_timerme_pb_navy_proto_rawDescGZIP(), []int{4}
}

func (x *CreateAnswerRequest) GetQuestionId() uint64 {
	if x != nil {
		return x.QuestionId
	}
	return 0
}

func (x *CreateAnswerRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type CreateAnswerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AnswerId      uint64                 `protobuf:"varint,1,opt,name=answer_id,json=answerId,proto3" json:"answer_id,omitempty"` //答案ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAnswerResponse) Reset() {
	*x = CreateAnswerResponse{}
	mi := &file_timerme_pb_navy_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAnswerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAnswerResponse) ProtoMessage() {}

func (x *CreateAnswerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_timerme_pb_navy_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAnswerResponse.ProtoReflect.Descriptor instead.
func (*CreateAnswerResponse) Descriptor() ([]byte, []int) {
	return file_timerme_pb_navy_proto_rawDescGZIP(), []int{5}
}

func (x *CreateAnswerResponse) GetAnswerId() uint64 {
	if x != nil {
		return x.AnswerId
	}
	return 0
}

type CreateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"` //用户名
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"` //密码
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_timerme_pb_navy_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_timerme_pb_navy_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_timerme_pb_navy_proto_rawDescGZIP(), []int{6}
}

func (x *CreateUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CreateUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type CreateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` //用户ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserResponse) Reset() {
	*x = CreateUserResponse{}
	mi := &file_timerme_pb_navy_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserResponse) ProtoMessage() {}

func (x *CreateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_timerme_pb_navy_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserResponse.ProtoReflect.Descriptor instead.
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return file_timerme_pb_navy_proto_rawDescGZIP(), []int{7}
}

func (x *CreateUserResponse) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetQuestionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuestionId    uint64                 `protobuf:"varint,1,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"` //问题ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQuestionRequest) Reset() {
	*x = GetQuestionRequest{}
	mi := &file_timerme_pb_navy_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQuestionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuestionRequest) ProtoMessage() {}

func (x *GetQuestionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_timerme_pb_navy_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuestionRequest.ProtoReflect.Descriptor instead.
func (*GetQuestionRequest) Descriptor() ([]byte, []int) {
	return file_timerme_pb_navy_proto_rawDescGZIP(), []int{8}
}

func (x *GetQuestionRequest) GetQuestionId() uint64 {
	if x != nil {
		return x.QuestionId
	}
	return 0
}

type GetQuestionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`     //问题标题
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"` //问题内容
	Tags          []string               `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`       //问题标签
	Uid           uint64                 `protobuf:"varint,4,opt,name=uid,proto3" json:"uid,omitempty"`        //用户ID
	Answers       []string               `protobuf:"bytes,5,rep,name=answers,proto3" json:"answers,omitempty"` //答案列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQuestionResponse) Reset() {
	*x = GetQuestionResponse{}
	mi := &file_timerme_pb_navy_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQuestionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuestionResponse) ProtoMessage() {}

func (x *GetQuestionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_timerme_pb_navy_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuestionResponse.ProtoReflect.Descriptor instead.
func (*GetQuestionResponse) Descriptor() ([]byte, []int) {
	return file_timerme_pb_navy_proto_rawDescGZIP(), []int{9}
}

func (x *GetQuestionResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GetQuestionResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *GetQuestionResponse) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *GetQuestionResponse) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *GetQuestionResponse) GetAnswers() []string {
	if x != nil {
		return x.Answers
	}
	return nil
}

var File_timerme_pb_navy_proto protoreflect.FileDescriptor

const file_timerme_pb_navy_proto_rawDesc = "" +
	"\n" +
	"\x15timerme_pb/navy.proto\x12\atimerme\"m\n" +
	"\x15CreateQuestionRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x12\n" +
	"\x04tags\x18\x03 \x03(\tR\x04tags\x12\x10\n" +
	"\x03uid\x18\x04 \x01(\x04R\x03uid\"9\n" +
	"\x16CreateQuestionResponse\x12\x1f\n" +
	"\vquestion_id\x18\x01 \x01(\x04R\n" +
	"questionId\"*\n" +
	"\x16ListQuestionIdsRequest\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x04R\x03uid\"<\n" +
	"\x17ListQuestionIdsResponse\x12!\n" +
	"\fquestion_ids\x18\x01 \x03(\x04R\vquestionIds\"P\n" +
	"\x13CreateAnswerRequest\x12\x1f\n" +
	"\vquestion_id\x18\x01 \x01(\x04R\n" +
	"questionId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"3\n" +
	"\x14CreateAnswerResponse\x12\x1b\n" +
	"\tanswer_id\x18\x01 \x01(\x04R\banswerId\"K\n" +
	"\x11CreateUserRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"-\n" +
	"\x12CreateUserResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\"5\n" +
	"\x12GetQuestionRequest\x12\x1f\n" +
	"\vquestion_id\x18\x01 \x01(\x04R\n" +
	"questionId\"\x85\x01\n" +
	"\x13GetQuestionResponse\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x12\n" +
	"\x04tags\x18\x03 \x03(\tR\x04tags\x12\x10\n" +
	"\x03uid\x18\x04 \x01(\x04R\x03uid\x12\x18\n" +
	"\aanswers\x18\x05 \x03(\tR\aanswers2\x92\x03\n" +
	"\tQAService\x12Q\n" +
	"\x0eCreateQuestion\x12\x1e.timerme.CreateQuestionRequest\x1a\x1f.timerme.CreateQuestionResponse\x12T\n" +
	"\x0fListQuestionIds\x12\x1f.timerme.ListQuestionIdsRequest\x1a .timerme.ListQuestionIdsResponse\x12K\n" +
	"\fCreateAnswer\x12\x1c.timerme.CreateAnswerRequest\x1a\x1d.timerme.CreateAnswerResponse\x12E\n" +
	"\n" +
	"CreateUser\x12\x1a.timerme.CreateUserRequest\x1a\x1b.timerme.CreateUserResponse\x12H\n" +
	"\vGetQuestion\x12\x1b.timerme.GetQuestionRequest\x1a\x1c.timerme.GetQuestionResponseB\x89\x01\n" +
	"\vcom.timermeB\tNavyProtoP\x01Z3github.com/betterde/focusly/internal/gen/timerme_pb\xa2\x02\x03TXX\xaa\x02\aTimerme\xca\x02\aTimerme\xe2\x02\x13Timerme\\GPBMetadata\xea\x02\aTimermeb\x06proto3"

var (
	file_timerme_pb_navy_proto_rawDescOnce sync.Once
	file_timerme_pb_navy_proto_rawDescData []byte
)

func file_timerme_pb_navy_proto_rawDescGZIP() []byte {
	file_timerme_pb_navy_proto_rawDescOnce.Do(func() {
		file_timerme_pb_navy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_timerme_pb_navy_proto_rawDesc), len(file_timerme_pb_navy_proto_rawDesc)))
	})
	return file_timerme_pb_navy_proto_rawDescData
}

var file_timerme_pb_navy_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_timerme_pb_navy_proto_goTypes = []any{
	(*CreateQuestionRequest)(nil),   // 0: timerme.CreateQuestionRequest
	(*CreateQuestionResponse)(nil),  // 1: timerme.CreateQuestionResponse
	(*ListQuestionIdsRequest)(nil),  // 2: timerme.ListQuestionIdsRequest
	(*ListQuestionIdsResponse)(nil), // 3: timerme.ListQuestionIdsResponse
	(*CreateAnswerRequest)(nil),     // 4: timerme.CreateAnswerRequest
	(*CreateAnswerResponse)(nil),    // 5: timerme.CreateAnswerResponse
	(*CreateUserRequest)(nil),       // 6: timerme.CreateUserRequest
	(*CreateUserResponse)(nil),      // 7: timerme.CreateUserResponse
	(*GetQuestionRequest)(nil),      // 8: timerme.GetQuestionRequest
	(*GetQuestionResponse)(nil),     // 9: timerme.GetQuestionResponse
}
var file_timerme_pb_navy_proto_depIdxs = []int32{
	0, // 0: timerme.QAService.CreateQuestion:input_type -> timerme.CreateQuestionRequest
	2, // 1: timerme.QAService.ListQuestionIds:input_type -> timerme.ListQuestionIdsRequest
	4, // 2: timerme.QAService.CreateAnswer:input_type -> timerme.CreateAnswerRequest
	6, // 3: timerme.QAService.CreateUser:input_type -> timerme.CreateUserRequest
	8, // 4: timerme.QAService.GetQuestion:input_type -> timerme.GetQuestionRequest
	1, // 5: timerme.QAService.CreateQuestion:output_type -> timerme.CreateQuestionResponse
	3, // 6: timerme.QAService.ListQuestionIds:output_type -> timerme.ListQuestionIdsResponse
	5, // 7: timerme.QAService.CreateAnswer:output_type -> timerme.CreateAnswerResponse
	7, // 8: timerme.QAService.CreateUser:output_type -> timerme.CreateUserResponse
	9, // 9: timerme.QAService.GetQuestion:output_type -> timerme.GetQuestionResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_timerme_pb_navy_proto_init() }
func file_timerme_pb_navy_proto_init() {
	if File_timerme_pb_navy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_timerme_pb_navy_proto_rawDesc), len(file_timerme_pb_navy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_timerme_pb_navy_proto_goTypes,
		DependencyIndexes: file_timerme_pb_navy_proto_depIdxs,
		MessageInfos:      file_timerme_pb_navy_proto_msgTypes,
	}.Build()
	File_timerme_pb_navy_proto = out.File
	file_timerme_pb_navy_proto_goTypes = nil
	file_timerme_pb_navy_proto_depIdxs = nil
}
